### ISSUE TITLE
TypeError: can't assign a NoneType to a Variable[CUDAType]

### ISSUE THREAD

**Issue by ffiioonnaa** [nghorbani/human_body_prior#10]
Hi，
   Thanks for your excellent works. when I follow the tutorial of VPoser PoZ Space for Body Models ,I meet a error in function bm.randomize_pose() .

Found Trained Model: /home/zhao/human_body_prior/vposer_v1_0/snapshots/TR00_E096.pt
Traceback (most recent call last):
  File "./snippet.py", line 12, in <module>
    bm.randomize_pose()
  File "/home/zhao/human_body_prior/human_body_prior/body_model/body_model.py", line 398, in randomize_pose
    self.root_orient.data[:] = root_orient
TypeError: can't assign a NoneType to a Variable[CUDAType]

How to deal with it?

**Comment by nghorbani** [comment]
Hi,
Thank you for finding this bug. We addressed the issue so you can now pull the master branch and access the tutorial as a Jupyter notebook at notebooks/vposer_poZ.ipynb
The new notebook interface for tutorials helps with rapid test of the tutorial code and assuring reproducibility.
