### ISSUE TITLE
from human_body_prior.tutorials.sample_body_pose import render_vposer_samples

### ISSUE THREAD

**Issue by yoonji-nam** [nghorbani/human_body_prior#14]
Hi, thanks for awesome work and sharing it.
Matter of fact, I'm running the notebooks/vposer_sampling.ipynb but have found out that:
<img width="845" alt="reportessue" src="https://user-images.githubusercontent.com/33611883/69223431-aea59380-0bbe-11ea-9590-6fb8a2ddd785.png">
it does not contain render_vposer_samples..

Have I missed something? Thanks in advance.

**Comment by nghorbani** [comment]
Hi, there was a bug in the notebooks after some clean up of the code. please pull the repo, install and try again. it should be fixed by now.

**Comment by yoonji-nam** [comment]
Thanks, now it works.
