### ISSUE TITLE
Question about vposer doceder

### ISSUE THREAD

**Issue by ZORAN666** [nghorbani/human_body_prior#15]
Can you tell me how to use the vposer decoder to recover the pose vector from smplify-x which model style is smpl to the pose vector from smplify? And the former pose vector has 32 parameters and the after pose vector has 72 parameters.
Thanks

**Comment by MichaelJBlack** [comment]
I’ll let Nima provide the details but you should be able to use Vposer to get the main joints of SMPL-X, since they are the same as SMPL.  You just won’t have a prior over the hand pose for facial pose.

Michael

**Comment by nghorbani** [comment]
@ZORAN666 we added a new tutorial for VPoser decoder [here](https://github.com/nghorbani/human_body_prior/blob/master/notebooks/vposer_decoder.ipynb). Please have a look and let me know if you have further questions.
