### ISSUE TITLE
reconstruction of root relative 3D human pose

### ISSUE THREAD

**Issue by Hunger-Prevails** [nghorbani/human_body_prior#18]
Hi, may I ask is there a way to conveniently reconstruct the root relative pose (a 21x3 numpy array in x, y and z coordinates) from a SMPL model using this package?

**Comment by nghorbani** [comment]
Yes that is possible. After you run the forward pass of the instantiated body, you can access the joints locations (xyz) in "Jtr" method of the returned results. A pseudo example code:
bm = BodyModel(bm_path)
body = bm(**body_parms)
print(body.Jtr.shape) # these are the joint positions that you are seeking in global space.
Good luck
Nima

**Comment by HelloEgg** [comment]
@nghorbani 
Hi. Thanks for the great work! 

It looks like decoded 32 latent values provide 63 parameters, which, I believe are xyz coordinates of 21 joints (as stated in TR*.ini file)

However, I couldn't find the correct order of 21 joints.

SMPL paper says it has 24 joints which are 

['Pelvis', 'L_Hip', 'R_Hip', 'Spine1', 'L_Knee', 'R_Knee',
'Spine2', 'L_Ankle', 'R_Ankle', 'Spine3', 'L_Foot', 'R_Foot',
'Neck', 'L_Collar', 'R_Collar', 'Head', 'L_Shoulder', 'R_Shoulder',
'L_Elbow', 'R_Elbow', 'L_Wrist', 'R_Wrist', 'L_Hand', 'R_Hand']

Which ones are missing? is the order correct?

Thank you so much for sharing your time!
