### ISSUE TITLE
decoder for pose_hand, pose_jaw and pose_eye?

### ISSUE THREAD

**Issue by HelloEgg** [nghorbani/human_body_prior#19]
Hello.

I successfully decoded body parameter which changes number of data column from 32 to 63.

I noticed that in order to render hand, I need 15*3*2 (which is, from my knowledge, is 15 joints * x y z * left and right hand). However, I couldn't figure out how to decode hand pose parameter which has only 12 pose parameters. 

It looks like I need to change 12 parameters to 45  data columns.

How can I solve it?

**Comment by nghorbani** [comment]
Hi, 
in [SMPLify-X](https://smpl-x.is.tue.mpg.de/) we only use variational human body poser, VPoser, as a prior for body parameters. For hand we use [MANO](https://mano.is.tue.mpg.de/) PCA space and for jaw and eyes we use no prior. So you correctly identified 12 parameters that are representing the hand, which correspond to MANO low-D PCA space. To use it with BodyModel presented in this repository you have to project it back to full pose space, e.g. 45 for each hand (90 in total), using the eigen vectors. For more explanation please refer to MANO.
if you had troubles there let me know.

**Comment by giuli13** [comment]
Hi, I am trying to fit the SMPLX model also to 3D hands and face joints. I dot not clearly understand how to decode the 3D joints location of hands and face in SMPLX pose space.

How can I solve it?
