### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by chenloveheimei** [nghorbani/human_body_prior#2]
Hello,My name is Long.
**this is my problem:**
Found Trained Model: /home/long/resource/model/human_pose_prior/vposer_v1_0/snapshots/TR00_E096.pt
Traceback (most recent call last):
  File "run.py", line 14, in <module>
    vertices = c2c(bm.forward().v)[0]
  File "/media/long/data/human_body_prior/human_body_prior/body_model/body_model.py", line 323, in forward
    new_body = super(BodyModelWithPoser, self).forward(pose_body=pose_body, **kwargs)
  File "/media/long/data/human_body_prior/human_body_prior/body_model/body_model.py", line 227, in forward
    dtype=self.dtype)
  File "/home/long/.local/lib/python3.6/site-packages/smplx/lbs.py", line 195, in lbs
    pose_offsets = torch.matmul(pose_feature, posedirs) \
RuntimeError: size mismatch, m1: [1 x 207], m2: [486 x 31425] at /pytorch/aten/src/THC/generic/THCTensorMathBlas.cu:268

Thx.

**Comment by nghorbani** [comment]
Hi there. Can you provide means to reproduce the issue?

from what i see, you have a pose_feature of size [1 x 207], and a posedirs of [486 x 31425]. 207 pose features, means you are providing smpl pose, but 486 posedirs means the model is expecting 54 smpl poses which are not there. So from current information i can guess that you are providing the path to "smpl model", yet your model_type is probably "smplh".

I might be able to help more in case i can reproduce the error from my side.

**Comment by chenloveheimei** [comment]
> Hi there. Can you provide means to reproduce the issue?
> 
> from what i see, you have a pose_feature of size [1 x 207], and a posedirs of [486 x 31425]. 207 pose features, means you are providing smpl pose, but 486 posedirs means the model is expecting 54 smpl poses which are not there. So from current information i can guess that you are providing the path to "smpl model", yet your model_type is probably "smplh".
> 
> I might be able to help more in case i can reproduce the error from my side.

**My demo:run.py**
from human_body_prior.body_model.body_model import BodyModelWithPoser
import trimesh
from human_body_prior.tools.omni_tools import copy2cpu as c2c

bm_path = '/home/long/resource/model/human_pose_prior/models/smplx/SMPLX_MALE.npz' # obtain from https://smpl-x.is.tue.mpg.de/downloads

smpl_exp_dir = '/home/long/resource/model/human_pose_prior/vposer_v1_0' # directory for the trained model along with the model code. obtain from https://smpl-x.is.tue.mpg.de/downloads

bm = BodyModelWithPoser(bm_path=bm_path, batch_size=1, model_type='smpl', poser_type='vposer', smpl_exp_dir=smpl_exp_dir).to('cuda')

bm.randomize_pose()

vertices = c2c(bm.forward().v)[0]
faces = c2c(bm.f)

mesh = trimesh.base.Trimesh(vertices, faces).show()

**The Error Line is:**
vertices = c2c(bm.forward().v)[0]

**Comment by nghorbani** [comment]
Thanks for further details. can you try: model_type='smplhf' ?

**Comment by chenloveheimei** [comment]
> smplx

i change the model_type='smplx' and the new Error:
long@long:/media/long/data/human_body_prior$ python run.py 
Traceback (most recent call last):
  File "run.py", line 9, in <module>
    bm = BodyModelWithPoser(bm_path=bm_path, batch_size=1, model_type='smplx', poser_type='vposer', smpl_exp_dir=smpl_exp_dir).to('cuda')
  File "/media/long/data/human_body_prior/human_body_prior/body_model/body_model.py", line 264, in __init__
    super(BodyModelWithPoser, self).__init__(**kwargs)
  File "/media/long/data/human_body_prior/human_body_prior/body_model/body_model.py", line 60, in __init__
    assert self.model_type in ['smpl', 'smplh', 'smplhf', 'mano_left', 'mano_right'], ValueError('model_type should be in smpl/smplh/smplhf/mano_left/mano_right.')
AssertionError: model_type should be in smpl/smplh/smplhf/mano_left/mano_right.

**Comment by chenloveheimei** [comment]
> Thanks for further details. can you try: model_type='smplx' ?
> The demo is updated to also include smplx by default.

Hello,guy.I`m alive.

**Comment by nghorbani** [comment]
you have to update your package install from pip or install from the githup repo

**Comment by chenloveheimei** [comment]
> you have to update your package install from pip or install from the githup repo

which package? I had updated them According to the ReadMe.md. and the update command is:python setup.py install.right? or I need to update them again?
