### ISSUE TITLE
what is the joint order in the full 63 dimentional SMPL body pose vector

### ISSUE THREAD

**Issue by maartenjv** [nghorbani/human_body_prior#20]
Hello,

I'm trying to find what the correspondence is between triplets in the 63 parameter axis angle pose vector and the 21 joints they refer to. Is this somewhere in the comments of one of the source files, or should I look somewhere else?

Thanks!

**Comment by maartenjv** [comment]
Just to be clear. Im referring to the anatomical meaning of the joints :)

**Comment by gulzainali98** [comment]
did you get the answer to this?

**Comment by gulzainali98** [comment]
@maartenjv

**Comment by maartenjv** [comment]
They match the order of the joint location keypoints, which you could plot to see what the anatomical meaning is. aa starts at keypoint 0+1 I think (i.e. the root has no axis angle value). Don't remember the details exactly though... 
Would still be nice to have this information available somewhere indeed.

**Comment by nghorbani** [comment]
[SMPL](https://smpl.is.tue.mpg.de/) originally has 72 joint parameters, i.e. 24x3 for 24 joints. In VPoser, as explained in [paper](https://smpl-x.is.tue.mpg.de/) we dont include root orientation (Pelvis) and hand end effectors. Therefor we reach 21 joints, e.g. 63 parameters (21x3).
 if you reshape the joint rotation vector into an array of  21x3 then name of each joint would be:
```
joint_names = {       
            0: 'L_Hip',
            3: 'L_Knee',
            6: 'L_Ankle',
            9: 'L_Foot',
         
            1: 'R_Hip',
            4: 'R_Knee',
            7: 'R_Ankle',
            10: 'R_Foot',
         
            2: 'Spine1',
            5: 'Spine2',
            8: 'Spine3',
            11: 'Neck',
            14: 'Head',
         
            12: 'L_Collar',
            15: 'L_Shoulder',
            17: 'L_Elbow',
            19: 'L_Wrist',
            13: 'R_Collar',
            16: 'R_Shoulder',
            18: 'R_Elbow',
            20: 'R_Wrist',
        }
```
