### ISSUE TITLE
Error Installing Human Body Prior

### ISSUE THREAD

**Issue by gulzainali98** [nghorbani/human_body_prior#24]
I am installing human body prior following the same procedure as shown in github. I am getting following errors. I installed configure through pip3 as provided in this github. 

> Could not find a version that satisfies the requirement configer>=1.4 (from human-body-prior==0.9.3.0) (from versions: 0.9, 1.1, 1.2, 1.2.1, 1.2.2, 1.2.3, 1.2.4, 1.3.0, 1.3.1)
No matching distribution found for configer>=1.4 (from human-body-prior==0.9.3.0)

**Comment by nghorbani** [comment]
please install configer with this command: 
`pip install git+https://github.com/MPI-IS/configer`
