### ISSUE TITLE
TypeError due to unexpected argument `dtype` while loading body_model

### ISSUE THREAD

**Issue by dpacgopinath** [nghorbani/human_body_prior#27]
Attempting to load smplh body model results in TypeError. This is because the lbs method in `vchoutas/smplx` does not take dtype as input argument (unlike `body_model/lbs.py`). See https://github.com/vchoutas/smplx/blob/master/smplx/lbs.py#L152-L162. I verified that removing `dtype` argument in the call to `lbs()` in `body_model/body_model.py` works for my use case.

```
  File "/Users/dgopinath/code/venv/fairmotion/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/Users/dgopinath/code/venv/fairmotion/lib/python3.7/site-packages/human_body_prior/body_model/body_model.py", line 233, in forward
    dtype=self.dtype)
TypeError: lbs() got an unexpected keyword argument 'dtype'
```

Would this be the right fix? If so, I can send a pull request. Since I'm using human_body_prior as a dependency via PyPI, could you help me by uploading a new package with the fix?

**Comment by nghorbani** [comment]
it wasnt a major things so i fixed it right away.

**Comment by dpacgopinath** [comment]
Thank you for fixing! Could you release a new version to PyPI so that code that is pip installed works too? https://pypi.org/project/human-body-prior/#history

On Aug 31, 2020, at 8:15 AM, Nima Ghorbani <notifications@github.com> wrote:

﻿

it wasnt a major things so i fixed it right away.

**Comment by nghorbani** [comment]
i made a tag
