### ISSUE TITLE
can't find the demo that single image generate a 3d model

### ISSUE THREAD

**Issue by chenloveheimei** [nghorbani/human_body_prior#3]
Hi.My name is Long.

I can't find the demo that single image generate a 3d model?
Is this project can do it or just train the 3d model?

**Comment by nghorbani** [comment]
[smplify-x](https://github.com/vchoutas/smplify-x) is essentially what you are looking for, e.g. given an image output a 3d model. 
human_body_prior is one component of the above mentioned pipeline.
hope this helps you.
