### ISSUE TITLE
Dimension error running VPoser Decoder with basic SMPL model

### ISSUE THREAD

**Issue by bronwynbiro** [nghorbani/human_body_prior#31]
Hi, 

I'm trying to run the VPoser Decoder demo found [here](https://github.com/nghorbani/human_body_prior/blob/master/notebooks/vposer_decoder.ipynb) with the standard SMPL model (not SMPL-X). I updated the path accordingly, and when I run the snippet

```
from human_body_prior.body_model.body_model import BodyModel
bm = BodyModel(bm_path=bm_path, batch_size=1).to('cuda')  
```
I get the error

```
ValueError                                Traceback (most recent call last)
<ipython-input-9-1fdea2200188> in <module>()
      2 from human_body_prior.body_model.body_model import BodyModel
      3 
----> 4 bm = BodyModel(bm_path=bm_path, batch_size=1).to('cuda')

/content/drive/MyDrive/human_body_prior-master/human_body_prior/body_model/body_model.py in __init__(self, bm_path, params, num_betas, batch_size, v_template, num_dmpls, path_dmpl, num_expressions, use_posedirs, dtype)
    113 
    114         shapedirs = smpl_dict['shapedirs'][:, :, :num_betas]
--> 115         self.register_buffer('shapedirs', torch.tensor(shapedirs, dtype=dtype))
    116 
    117         if self.model_type == 'smplx':

ValueError: too many dimensions 'Select'
```

Any advice for how to fix this would be appreciated!

**Comment by bronwynbiro** [comment]
Once I ran the cleaning script to remove chumpy from my .pkl file, the error went away.

**Comment by OOF-dura** [comment]
> Once I ran the cleaning script to remove chumpy from my .pkl file, the error went away.
.
Where is the cleaning script?

Thanks!

**Comment by bronwynbiro** [comment]
The script and info on how to run it are [here](https://github.com/vchoutas/smplx/tree/master/tools) :)
