### ISSUE TITLE
Where to get vposer_v2_05?

### ISSUE THREAD

**Issue by lwcode** [nghorbani/human_body_prior#32]
On this site https://smpl-x.is.tue.mpg.de/downloads, I just can find vposer_v1_0 version, where is vposer_v2_05?

**Comment by nghorbani** [comment]
great question! I just placed them under smplx page: https://smpl-x.is.tue.mpg.de/downloads

**Comment by jinfagang** [comment]
@nghorbani 
![image](https://user-images.githubusercontent.com/21303438/148963166-f267368d-c3f2-4af9-a25c-7c61cc68965d.png)

**Comment by chen-wl20** [comment]
@nghorbani  @lucasjinreal  I also encountered the problem of 404 not found. Can you re-upload this file? Thank you very much！
