### ISSUE TITLE
error running BodyModelWithPoser with the smplx model

### ISSUE THREAD

**Issue by maartenjv** [nghorbani/human_body_prior#4]
I have and issue with this code snippet (https://github.com/nghorbani/human_body_prior/blob/master/human_body_prior/body_model/README.md)

It seems that the code tries to load something related to the MANO model, but this path/file is defined as “None”

self.poser_handL_pt, self.poser_handL_ps = poser_loader(mano_exp_dir)

I did find some files and information related to smplh and mano here

https://github.com/vchoutas/smplx/tree/master/tools

But these seem to be all .pkl files and not train model .pt files...

Any suggestions?

Thanks,

-Maarten

**Comment by nghorbani** [comment]
Hi Maarten,
I fixed issue already in the master branch. please update your installation and it should work.
