### ISSUE TITLE
How can i get the SMPLH body model path in npz form

### ISSUE THREAD

**Issue by sosown123** [nghorbani/human_body_prior#6]

**Comment by sosown123** [comment]
![image](https://user-images.githubusercontent.com/49749924/62418980-f7394f80-b6a8-11e9-8d56-17ac83c6f293.png)

**Comment by nghorbani** [comment]
Well the title of the issue and the description you give is different so i am going to address both :)
for smplh path you have to ask [MANO](http://mano.is.tue.mpg.de/) folks or simply get the pkl file and turn it into a numpy npz. i can give you a code for the latter if needed. 

On the second issue, the error gets back to [configer](https://github.com/nghorbani/configer). please clone its repository and follow the installation commands provided in the repository. the error specifically complains about a broken syntax from python 2.7 that is used in python 3, namely iteritems(), which should be replaced by items().

Cheers, Nima
