### ISSUE TITLE
Inconsistent hand parameters 

### ISSUE THREAD

**Issue by hanweikung** [nghorbani/human_body_prior#60]
I generated a model using the [smplify-x](https://github.com/vchoutas/smplify-x) fitting code and attempted to load the model in Blender using this [Blender add-on](https://gitlab.tuebingen.mpg.de/jtesch/smplx_blender_addon). However it seemed the Blender add-on expected a different number of hand parameters from the model and failed to load the hand poses. Specifically, the generated model had 12 parameters for each hand, but the Blender add-on expected 45 parameters for each.

How do I load the hand correctly? Thank you.

**Comment by ujemd** [comment]
maybe this helps:

https://github.com/nghorbani/human_body_prior/issues/19#issuecomment-586188360

**Comment by hanweikung** [comment]
Thank you for your reply. I got it working by turning off use_pca in cfg_files/fit_smplx.yaml

`use_pca: False`
