### ISSUE TITLE
Estimation from human3.6m joints

### ISSUE THREAD

**Issue by paulgrassler** [nghorbani/human_body_prior#61]
Hey, I've been wondering if it would be possible for you to give me a rough outline of what I would need to do, so that I could use Human3.6M 3d joint positions (16 joints) as input and get shape and pose estimations for SMPL as output. It should be possible, right? Would appreciate any help, thank you in advance!

**Comment by MichaelJBlack** [comment]
The SMPL joint regressor J(.) gives you the 3D joint locations.  You then just need to optimize shape and pose parameters to minimize the 3D joint location error.  You can look at SMPLify and how this is done when fitting to 2D joints.  Fitting to 3D joints is much easier.
